### PR TITLE
updated some codes

### PR DESCRIPTION
**Pull request by debck**

### CODE REVIEW

**Comment by sr6033** [comment]
Don't add `scanf()` in place of `cin`. Remove those edits in your PR.

**Comment by debck** [comment]
i just added a new .cpp file of binary search

**Comment by sr6033** [comment]
Kindly read `readme.md`. 
Always specify the problem statement at the top using comments.

**Comment by debck** [comment]
i added the problem statements .
plz check it

**Comment by sibasish14** [comment]
@debck you should have minimum number of commits in a single PR. Try to squash them into one commit.

**Pull request merged**
